# Generated by Django 5.2.4 on 2025-07-24 12:23

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, unique=True),
        ),
    ]
